# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Rebecca v2"
license = "Apache-2.0"
licenselink = "https://github.com/rebeccajae/hugo-theme-rebeccajae2/blob/master/LICENSE"
description = "A theme for my website. New version."
homepage = "https://www.rebeccapruim.com/"
tags = []
features = []
min_version = "0.38"

[author]
  name = "Rebecca Pruim"
  homepage = "https://www.rebeccapruim.com/"
